[package]
name = "univ-rennes"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Léana 江 <@leana8959>"]
license = "MIT"
description = "An opinionated, non official template for University of Rennes"
homepage = "https://github.com/leana8959/univ-rennes.typ"
repository = "https://github.com/leana8959/univ-rennes.typ"
keywords = ["university", "rennes", "template", "france"]
categories = ["template"]
exclude = [".gitignore", "shell.nix", "Justfile"]

[template]
path = "examples/"
entrypoint = "rapport-stage.typ"
